df_path: ../../monet/csv/nasbench201.csv
dataset: cifar10
search:
  level: 2
  nrpa_alpha: 0.1
  softmax_temp: 2
  playouts_per_selection: 1
  C: 0.1
  n_iter: 3000
  rave_b: 0.1
disable_tqdm: true
seed: 0
