dataset: cifar10
optimizer: rs
out_dir: run
search:
  acq_fn_optimization: mutation
  acq_fn_type: its
  checkpoint_freq: 5000
  debug_predictor: false
  encoding_type: path
  epochs: 150
  fidelity: 200
  k: 25
  max_mutations: 1
  num_arches_to_mutate: 2
  num_candidates: 100
  num_ensemble: 3
  num_init: 10
  population_size: 30
  predictor_type: bananas
  sample_size: 10
search_space: nasbench201
seed: 44
